Feat(interceptor): add transformer interceptor
loggie-io/loggie pull request #267
Opened 2022-06-27 01:59 UTC by ethfoo

#### Proposed Changes:

* add transformer interceptor

#### Which issue(s) this PR fixes:

None

#### Additional documentation:

```yaml
- interceptors:
  - type: transformer
    actions:
    - if: <conditions>
      then:
      - action: <action>
        <other options>
      - action: <action>
      else:
      - action: <action>
    - if: <conditions>
      then:
      - action: <action>      
    - action: <action>
```

2022-06-28 09:00 UTC, iamyeka requested changes

2022-06-28 09:02 UTC, ethfoo commented on pkg/interceptor/transformer/condition/oneof.go
> +	OneOfName     = "oneof"
ok

2022-06-30 05:58 UTC, ethfoo commented on pkg/interceptor/transformer/condition/greater.go
> +func (eq *Greater) Check(e api.Event) bool {
done

2022-06-30 06:06 UTC, ethfoo commented on pkg/interceptor/transformer/condition/isnull.go
> +	IsNullUsageMsg = "usage: isNull(key)"
done

2022-06-30 06:07 UTC, ethfoo commented on pkg/interceptor/transformer/action/dropevent.go
> +	DropEventName     = "dropEvent"
因为drop再normalize里面表示删除一个字段，所以这里为了不让用户混淆，强调了一下是dropEvent

2022-06-30 06:59 UTC, merged